name: CI Build and Push Docker Images

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: yarn install --frozen-lockfile

      - name: Run Linter
        working-directory: ./frontend
        run: yarn lint

      - name: Build Frontend
        working-directory: ./frontend
        run: yarn build

      # Login no GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Construir e enviar a imagem do Backend
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend 
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:latest

      # Construir e enviar a imagem do Frontend
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:latest
